# Generated by Django 5.1.4 on 2025-03-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_date_of_birth_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='idontknow',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='usname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
