# Generated by Django 5.1.4 on 2025-03-01 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('teacher', '0003_teacher_idontknow_teacher_usname'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teach_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image'),
        ),
    ]
