# Generated by Django 5.1.4 on 2025-03-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_teach_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teachprofile_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
