# Generated by Django 5.1.4 on 2025-03-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_teachprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='usname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
