# Generated by Django 5.1.4 on 2025-03-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_teacher_usname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
