# Generated by Django 5.1.4 on 2025-01-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='7OSFHOdQJGn01vNkTAqBsjZkNkrsLGaZ', editable=False, max_length=32, unique=True),
        ),
    ]
