# Generated by Django 5.1.4 on 2025-01-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='CIHefmFjDb1JbukZ7BzsdOUElQEzhhAz', editable=False, max_length=32, unique=True),
        ),
    ]
