# Generated by Django 5.1.4 on 2025-01-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='core/img/'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='5W2pPNJBZePujBPdNii1yhNPXA1Anp9H', editable=False, max_length=32, unique=True),
        ),
    ]
