# Generated by Django 5.1.4 on 2025-01-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_has_sub_customuser_is_top_management_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='student',
            new_name='student_profile',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='teacher',
            new_name='teacher_profile',
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='FdPQ7LkgBflPt8cbVCCAnJSyh9hxDUbr', editable=False, max_length=32, unique=True),
        ),
    ]
