# Generated by Django 5.1.4 on 2025-01-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Ss1V2Dbr3uZtzfB0Hlt5ILpjSnNTFejj', editable=False, max_length=32, unique=True),
        ),
    ]
