# Generated by Django 5.1.4 on 2025-01-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_student_customuser_student_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='TuAOxl7BNX1boHcpW1zUyOnULOpYkwvl', editable=False, max_length=32, unique=True),
        ),
    ]
