# Generated by Django 5.1.4 on 2025-02-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='9KnsV2wPIMvqzPLeRVWUMK9f7KxTQW5R', editable=False, max_length=32, unique=True),
        ),
    ]
