# Generated by Django 5.1.4 on 2025-02-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='eLoBLGqw5ycCCXhfvCio3aSDhRijBUsC', editable=False, max_length=32, unique=True),
        ),
    ]
