# Generated by Django 5.1.4 on 2025-02-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='kaMLJLi1CG5OqK8rjUSmEumgvKHvtuQZ', editable=False, max_length=32, unique=True),
        ),
    ]
