# Generated by Django 5.1.4 on 2025-02-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gROfYyG19aiNJrgBiQqkUdhGCkW5fUft', editable=False, max_length=32, unique=True),
        ),
    ]
