# Generated by Django 5.1.4 on 2025-02-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='feWoqmsX7DfIHpW8jDX5RFxN7NSJa9CF', editable=False, max_length=32, unique=True),
        ),
    ]
