# Generated by Django 5.1.4 on 2025-02-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='5Vxp3zKepnWRRrXvvwJTaZsXDubgcKZM', editable=False, max_length=32, unique=True),
        ),
    ]
