# Generated by Django 5.1.4 on 2025-02-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='BxpltpwQA80MjP7sq4BmOizBl6D1njVN', editable=False, max_length=32, unique=True),
        ),
    ]
