# Generated by Django 5.1.4 on 2025-02-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='5zt9gMQtKSqT25Um7ziYkKUkdUY1ORxu', editable=False, max_length=32, unique=True),
        ),
    ]
