# Generated by Django 5.1.4 on 2025-02-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_customuser_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='7SThrqefYUjlSC1ETH5K0bcmNveJ5ktr', editable=False, max_length=32, unique=True),
        ),
    ]
