# Generated by Django 5.1.4 on 2025-02-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='dSin863TWaZqHY5O39uFsv02BznzCKLd', editable=False, max_length=32, unique=True),
        ),
    ]
