# Generated by Django 5.1.4 on 2025-02-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='dDObRMMlqqMI5q92BeIf92YfWQKcqW57', editable=False, max_length=32, unique=True),
        ),
    ]
