# Generated by Django 5.1.4 on 2025-02-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='eKCoZ8Tw3IPpjQx2dUAbWkA94qXpDycw', editable=False, max_length=32, unique=True),
        ),
    ]
