# Generated by Django 5.1.4 on 2025-02-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='M4gZ3gqOdwoTEJ1ZfyGMkCoZhjwFLIXP', editable=False, max_length=32, unique=True),
        ),
    ]
