# Generated by Django 5.1.4 on 2025-02-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='w1KlQ7h3Dy74v8EAbwanK0CjznUoubt4', editable=False, max_length=32, unique=True),
        ),
    ]
