# Generated by Django 5.1.4 on 2025-02-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='kJomj33Q2MQjpMQ0YfcBS3PJsAgEnlO5', editable=False, max_length=32, unique=True),
        ),
    ]
