# Generated by Django 5.1.4 on 2025-03-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='t7QR6JJMUo07zk0jAqIeHkc26qzvEm4o', editable=False, max_length=32, unique=True),
        ),
    ]
