# Generated by Django 5.1.4 on 2025-03-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='U7S2RWrd34vy3cJUS1wtrOat1rklhBum', editable=False, max_length=32, unique=True),
        ),
    ]
