# Generated by Django 5.1.4 on 2025-03-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='O3AmpABHQvbEY5zvGaf5VKBwy3RPLOyu', editable=False, max_length=32, unique=True),
        ),
    ]
