# Generated by Django 5.1.4 on 2025-03-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='lksQ9vFk9JHtkQ07ukLGbIuJCW8hzEvw', editable=False, max_length=32, unique=True),
        ),
    ]
