# Generated by Django 5.1.4 on 2025-03-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='V0FWZQzojLacSooH9kH7PvwNVYUTJrAu', editable=False, max_length=32, unique=True),
        ),
    ]
