# Generated by Django 5.1.4 on 2025-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='EWtu4xO2lpLwK88Zykc1IZ938am4k8ik', editable=False, max_length=32, unique=True),
        ),
    ]
