# Generated by Django 5.1.4 on 2025-03-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='4Gm1cCvmdY6L0XCW3Vo2wOvVkMc2SL3a', editable=False, max_length=32, unique=True),
        ),
    ]
