# Generated by Django 5.1.4 on 2025-03-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Vz32TtrnbqZqxjb5cdgz95bACkNmtbDC', editable=False, max_length=32, unique=True),
        ),
    ]
