# Generated by Django 5.1.4 on 2025-03-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='tf5BvEEEwfqPcL2AcAJOt3pg8Kvz2kKS', editable=False, max_length=32, unique=True),
        ),
    ]
