# Generated by Django 5.1.4 on 2025-03-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='0kjkUn9LTDv5yJF55Ch6uUiPpNFr391C', editable=False, max_length=32, unique=True),
        ),
    ]
