# Generated by Django 5.1.4 on 2025-03-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='zQN9lIXdTcgLoL1U0IXH5g2cVQJGFr8i', editable=False, max_length=32, unique=True),
        ),
    ]
