# Generated by Django 5.1.4 on 2025-03-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='dE9N230EQud87K4tfAsDx45xVLizNsp3', editable=False, max_length=32, unique=True),
        ),
    ]
