# Generated by Django 5.1.4 on 2025-03-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='CNI18IkZfW5X4hUx5qsmDno1cQqIbZYT', editable=False, max_length=32, unique=True),
        ),
    ]
