# Generated by Django 5.1.4 on 2025-03-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gmxUx7EDmTV9bW0OZJUXaLsH1Ljr1Foj', editable=False, max_length=32, unique=True),
        ),
    ]
