# Generated by Django 5.1.4 on 2025-03-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='VazwexzCFCKgIsFg0tRBwgUgiwBdPVO6', editable=False, max_length=32, unique=True),
        ),
    ]
