# Generated by Django 5.1.4 on 2025-03-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='5vxoQ0MXXcfsVSOBL2SLCvywJUo3s9XV', editable=False, max_length=32, unique=True),
        ),
    ]
