# Generated by Django 5.1.4 on 2025-03-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Uu7mTDpMCcXPiXNdT9NblEHz9BPbR7i6', editable=False, max_length=32, unique=True),
        ),
    ]
