"""
Django settings for home project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import dj_database_url
from pathlib import Path, os
from decouple import config as env_config


# import cloudinary_storage


#back up config
try:
    from decouple import config as env_config
except ImportError:
    import os
    env_config = os.environ.get

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-4=23-u*8$4&csao1)-ltu+y9f4spa)07ub07)0shg*)uvpaq21'
# SECRET_KEY = env_config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False
# DEBUG = True
# DEBUG = env_config("DJANGO_DEBUG", cast=bool, default=True)

# ALLOWED_HOSTS = []
"""
Django settings for django_24 project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--$@crdyu3i8k*q^jy4jo21k)d0kxq-21e)jx5cb_yi&-j*fix)'
# SECRET_KEY =  os.getenv('SECRET_KEY')



ALLOWED_HOSTS = ["school-management-8p1f.onrender.com", '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    # 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'school',
    'student',
    'subject',
    'department',
    'teacher',
    'testeval',
    'core',


    # 'cloudinary'
    # 'cloudinary_storage'

    'images',

    'import_export',

  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    #for deployment
    "whitenoise.middleware.WhiteNoiseMiddleware",

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'home.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'home.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# online DB
DATABASES["default"] = dj_database_url.parse("postgresql://giltead_posql_render_user:hksRQhjfkQz0fb0hblDV95YnCkahL7F0@dpg-cv1l2ld6l47c73fg5l0g-a.oregon-postgres.render.com/giltead_posql_render")

# postgresql://giltead_posql_render_user:hksRQhjfkQz0fb0hblDV95YnCkahL7F0@dpg-cv1l2ld6l47c73fg5l0g-a.oregon-postgres.render.com/giltead_posql_render


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

# STATIC_ROOT = BASE_DIR/'assets'

# STORAGES = {
#     # ...
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = 'static/'

# CSS_LOCATION = os.path.join(BASE_DIR,'static')



STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR/'static']
STATIC_ROOT = BASE_DIR/'assets'

if DEBUG == False:
    STATIC_ROOT = "http://127.0.0.1:8000/static/assets"

CSS_LOCATION = os.path.join(BASE_DIR,'static')

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

#prod conditions
# if DEBUG:
#     STATICFILES_DIRS = [os.path.join(BASE_DIR/'static')]
# else:
#     STATIC_ROOT = os.path.join(BASE_DIR/'static')



MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# CLOUDFLARE_R2_BUCKET=env_config("CLOUDFLARE_R2_BUCKET", cast=str, default="gilead")
# CLOUDFLARE_R2_ACCESS_KEY=env_config("CLOUDFLARE_R2_ACCESS_KEY")
# CLOUDFLARE_R2_SECRET_KEY=env_config("CLOUDFLARE_R2_SECRET_KEY")
# CLOUDFLARE_R2_BUCKET_ENDPOINT=env_config("CLOUDFLARE_R2_BUCKET_ENDPOINT")


# CLOUDFLARE_R2_CONFIG_OPTIONS = {
#     "bucket_name": CLOUDFLARE_R2_BUCKET,
#     "access_key": CLOUDFLARE_R2_ACCESS_KEY,
#     "secret_key": CLOUDFLARE_R2_SECRET_KEY,
#     "endpoint_url": CLOUDFLARE_R2_BUCKET_ENDPOINT,
#     "default_acl": "public-read",
#     "signature_version": "s3v4",
# }

# django staticfiles config for storages
# STORAGES = {
#     # ...
#     "default": {
#         # "BACKEND": "storages.backends.s3.S3Storage", #from django-storages[s3]
#         "BACKEND": "helpers.cloudflare.storages.MediaFileStorage", #from django-storages[s3]
#         # "BACKEND": "storages.backends.s3.S3Storage",
#         "OPTIONS": CLOUDFLARE_R2_CONFIG_OPTIONS,
#         # "OPTIONS": {
#         #     "bucket_name": CLOUDFLARE_R2_BUCKET,
#         #     "location": "media", 
#         # },
#     },
#     "staticfiles": {
#         # "BACKEND": "storages.backends.s3.S3Storage",
#         # "BACKEND": "helpers.cloudflare.storages.StaticFileStorage",
#         # "BACKEND": "storages.backends.s3.S3Storage",
#         # "OPTIONS": CLOUDFLARE_R2_CONFIG_OPTIONS,
#         # "OPTIONS": {
#         #     "bucket_name": CLOUDFLARE_R2_BUCKET,
#         #     "location": "static", 
#         # },
#         "BACKEND": "helpers.cloudflare.storages.StaticFileStorage",
#         "OPTIONS": CLOUDFLARE_R2_CONFIG_OPTIONS,
#     }
# }


#  add this for authentication

AUTH_USER_MODEL = 'core.CustomUser'  # Adjust 'core' to the app where CustomUser is defined
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default backend
)


# Use console email backend for local development
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# settings.py

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'  # Replace with your email
# EMAIL_HOST_PASSWORD = 'your-email-password'  # Replace with your email password or app-specific password


# CLOUDFLARE_STORAGE = {

# }


#try3
# CLOUDFLARE_ACCOUNT_ID=env_config("CLOUDFLARE_ACCOUNT_ID")
# CLOUDFLARE_API_KEY=env_config("CLOUDFLARE_API_KEY")
# CLOUDFLARE_ACCOUNT_HASH=env_config("CLOUDFLARE_ACCOUNT_HASH")
# CLOUDFLARE_IMAGES_DOMAIN=env_config("CLOUDFLARE_IMAGES_DOMAIN", default='imagedelivery.net')
# CLOUDFLARE_EMAIL=env_config("CLOUDFLARE_EMAIL")
#
CLOUDFLARE_ACCOUNT_ID="bf4a9e29eb43a6e2ba9693463bf43826"
CLOUDFLARE_API_KEY="1WeDSG7AjzQRF_O1_4X5K2JrsiLCj0qSLqHZ0B0N"
CLOUDFLARE_ACCOUNT_HASH="FGazjujafzdf38AXQFJ0qw"
CLOUDFLARE_IMAGES_DOMAIN="imagedelivery.net"
CLOUDFLARE_EMAIL="nancydev.dev@gmail.com"
# CLOUDFLARE_ACCOUNT_ID     =  os.getenv('CLOUDFLARE_ACCOUNT_ID')
# CLOUDFLARE_API_KEY        =  os.getenv('CLOUDFLARE_API_KEY')
# CLOUDFLARE_ACCOUNT_HASH   =  os.getenv('CLOUDFLARE_ACCOUNT_HASH')
# CLOUDFLARE_IMAGES_DOMAIN  =  os.getenv('CLOUDFLARE_IMAGES_DOMAIN')
# CLOUDFLARE_EMAIL          =  os.getenv('CLOUDFLARE_EMAIL')


STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

MEDIA_URL ='/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# added session expiratn
# SESSION_EXPIRE_SECONDS = 3600  # 1 hour
# SESSION_EXPIRE_SECONDS = 600  # 30min
SESSION_EXPIRE_SECONDS = 600  # 30min
# By default, the session will expire X seconds after the start of the session. To expire the session X seconds after the last activity, use the following setting:
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
# By default, last activiy will be grouped per second. To group by different period use the following setting:
# SESSION_EXPIRE_AFTER_LAST_ACTIVITY_GRACE_PERIOD = 60 # group by minute
SESSION_EXPIRE_AFTER_LAST_ACTIVITY_GRACE_PERIOD = 60 # group by minute
# To redirect to a custom URL define the following setting:
SESSION_TIMEOUT_REDIRECT = 'authentication/login/'

# 
SESSION_COOKIE_AGE = 600
SESSION_SAVE_EVERY_REQUEST = True
SESSION_TIMEOUT_REDIRECT = 'authentication/login/'
LOGIN_URL = '/authentication/login/'
