# Generated by Django 5.1.4 on 2025-01-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=250, unique=True)),
                ('class_code', models.CharField(max_length=250, unique=True)),
                ('class_department', models.CharField(blank=True, max_length=250, null=True)),
                ('other', models.CharField(blank=True, max_length=250, null=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('modified_by', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
