# Generated by Django 5.1.4 on 2025-02-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='exact_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
