# Generated by Django 5.1.4 on 2025-02-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_settings_exact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='added_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='other',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
