# Generated by Django 5.1.4 on 2025-01-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='clientLogo',
            field=models.ImageField(default='default_logo.jpg', upload_to='company_logos/img/'),
        ),
    ]
