# Generated by Django 5.1.4 on 2025-01-26 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('student', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('total_coeff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observation', models.TextField(blank=True, null=True)),
                ('freefield', models.CharField(blank=True, max_length=100, null=True)),
                ('freefield2', models.CharField(blank=True, max_length=100, null=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Eval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('titre', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coef', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subject_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('teacher', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rank', models.DecimalField(decimal_places=0, max_digits=10)),
                ('general_subjs_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prof_subjs_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('best_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('worst_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('firstterm_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('secondterm_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_of_report_card_generation', models.DateField(auto_now_add=True)),
                ('term', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=100, null=True)),
                ('resumption', models.CharField(blank=True, max_length=100, null=True)),
                ('subj_moy', models.CharField(blank=True, max_length=100, null=True)),
                ('moreinfo', models.TextField(blank=True, null=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentreportcard', to='student.student')),
            ],
            options={
                'unique_together': {('student_rank', 'date_of_report_card_generation')},
            },
        ),
    ]
