# Generated by Django 5.1.4 on 2025-01-17 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0008_alter_student_name'),
        ('subject', '0004_subject_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('titre', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coef', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subject_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('teacher', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
