# Generated by Django 5.1.4 on 2025-01-28 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('student', '0002_student_specialty'),
        ('subject', '0001_initial'),
        ('testeval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classranking',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.specialty'),
        ),
        migrations.CreateModel(
            name='TestMoySpecialtySubjClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('test_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observation', models.TextField(blank=True, null=True)),
                ('freefield', models.CharField(blank=True, max_length=100, null=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.specialty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
