# Generated by Django 5.1.4 on 2025-01-18 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_name'),
        ('testeval', '0002_alter_eval_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rank', models.DecimalField(decimal_places=0, max_digits=10)),
                ('general_subjs_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prof_subjs_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('best_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('worst_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('firstterm_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('secondterm_avr', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_of_report_card_generation', models.DateField(auto_now_add=True)),
                ('term', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=100, null=True)),
                ('resumption', models.CharField(blank=True, max_length=100, null=True)),
                ('moreinfo', models.TextField(blank=True, null=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentreportcard', to='student.student')),
            ],
            options={
                'unique_together': {('student_rank', 'date_of_report_card_generation')},
            },
        ),
    ]
