# Generated by Django 5.1.4 on 2025-01-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeval', '0002_classranking_specialty_testmoyspecialtysubjclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmoyspecialtysubjclass',
            name='subj_coef',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
