# Generated by Django 5.1.4 on 2025-01-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeval', '0003_reportcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='subj_moy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
