# Generated by Django 5.1.4 on 2025-02-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeval', '0004_classranking_academic_year_eval_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='annual_subj_passed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='annuelle_avr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='first_subj_passed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='second_subj_passed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='third_subj_passed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
