# Generated by Django 5.1.4 on 2025-01-18 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_classroom_modified_by'),
        ('student', '0008_alter_student_name'),
        ('testeval', '0004_reportcard_subj_moy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('total_coeff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observation', models.TextField(blank=True, null=True)),
                ('freefield', models.CharField(blank=True, max_length=100, null=True)),
                ('freefield2', models.CharField(blank=True, max_length=100, null=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
