# Generated by Django 5.1.4 on 2025-02-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeval', '0005_reportcard_annual_subj_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='gen_coeff',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='gen_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='prof_coeff',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='prof_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
