# Generated by Django 5.1.4 on 2025-02-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_specialty'),
        ('testeval', '0006_reportcard_gen_coeff_reportcard_gen_total_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'student_rank', 'term', 'academic_year', 'date_of_report_card_generation')},
        ),
    ]
