# Generated by Django 5.1.4 on 2025-03-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeval', '0008_eval_teacher_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classranking',
            name='academic_year',
            field=models.CharField(default='2024/2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='eval',
            name='academic_year',
            field=models.CharField(default='2024/2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='testmoyspecialtysubjclass',
            name='academic_year',
            field=models.CharField(default='2024/2025', max_length=100),
        ),
    ]
