# Generated by Django 5.1.4 on 2025-03-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_settings_added_by_settings_is_actif_and_more'),
        ('student', '0015_alter_student_slug'),
        ('testeval', '0010_eval_sec_title_eval_sec_titre_eval_sec_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClasRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('student_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observation', models.TextField(blank=True, null=True)),
                ('academic_year', models.CharField(default='2024/2025', max_length=100)),
                ('spec_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('class_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('school_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('freefield1', models.CharField(blank=True, max_length=100, null=True)),
                ('freefield2', models.CharField(blank=True, max_length=100, null=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.specialty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
