# Generated by Django 5.1.4 on 2025-03-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_student_slug'),
        ('testeval', '0012_reportcard_thirdterm_avr_alter_reportcard_best_avr_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'date_of_report_card_generation', 'student_rank', 'term', 'academic_year')},
        ),
    ]
