# Generated by Django 5.1.4 on 2025-03-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_student_slug'),
        ('testeval', '0013_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'date_of_report_card_generation', 'student_rank', 'term', 'is_actif', 'academic_year')},
        ),
    ]
