# Generated by Django 5.1.4 on 2025-04-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeval', '0018_alter_eval_seqone_is_absent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='class_moy_avr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
