# Generated by Django 5.1.4 on 2025-01-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
