# Generated by Django 5.1.4 on 2025-02-22 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('student', '0002_student_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image'),
        ),
    ]
