# Generated by Django 5.1.4 on 2025-01-14 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_student_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='created_by',
        ),
        migrations.AddField(
            model_name='parent',
            name='added_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='is_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='modified_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='added_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='modified_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
