# Generated by Django 5.1.4 on 2025-02-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_stud_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='carer_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='carer_mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
