# Generated by Django 5.1.4 on 2025-01-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_parent_alter_student_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
