# Generated by Django 5.1.4 on 2025-02-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_parent_carer_email_alter_parent_carer_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='minesec_ident_num',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
