# Generated by Django 5.1.4 on 2025-01-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_student_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
