# Generated by Django 5.1.4 on 2025-02-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sch_status',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
