# Generated by Django 5.1.4 on 2025-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_parent_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
