# Generated by Django 5.1.4 on 2025-02-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_sch_status_alter_student_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='father_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
