# Generated by Django 5.1.4 on 2025-02-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_parent_father_email_alter_parent_father_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sch_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
