# Generated by Django 5.1.4 on 2025-03-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_sch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
