# Generated by Django 5.1.4 on 2025-03-02 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_settings_added_by_settings_is_actif_and_more'),
        ('student', '0011_alter_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.classroom'),
        ),
    ]
