# Generated by Django 5.1.4 on 2025-03-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_student_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='minesec_ident_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
