# Generated by Django 5.1.4 on 2025-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_student_minesec_ident_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
