# Generated by Django 5.1.4 on 2025-01-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_classroom_modified_by'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='classroom',
        ),
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.ManyToManyField(to='school.classroom'),
        ),
    ]
