# Generated by Django 5.1.4 on 2025-01-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_remove_subject_classroom_subject_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='coef',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='fr_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
