# Generated by Django 5.1.4 on 2025-01-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_subject_coef_subject_fr_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
