# Generated by Django 5.1.4 on 2025-01-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_subject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='coef',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
