# Generated by Django 5.1.4 on 2025-02-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('school', '0003_settings_added_by_settings_is_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='depart_specialty', to='school.specialty'),
        ),
    ]
