# Generated by Django 5.1.4 on 2025-02-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_specialties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='depart_class',
        ),
    ]
